#!/bin/bash
set +x
env | sort
stable=0.7.2
for V in master 0.7 0.7.2; do
    docker build --build-arg JUPYTERHUB_VERSION=$V -t $DOCKER_REPO:$V .
done
docker tag $DOCKER_REPO:$stable $IMAGE_NAME

# tag X.Y for master
master_v=$(docker run --rm -it $DOCKER_REPO:master jupyterhub --version)
split=( ${master_v//./ } )
master_xy="${split[0]}.${split[1]}"
docker tag $DOCKER_REPO:master $DOCKER_REPO:$master_xy
